<?php

/**
 * BaseProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $sf_guard_user_id
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property integer $nb_display_results
 * @property string $language
 * @property string $country
 * @property string $search_filter
 * @property string $series
 * @property string $hash
 * @property sfGuardUser $User
 * 
 * @method integer     getSfGuardUserId()      Returns the current record's "sf_guard_user_id" value
 * @method string      getFirstName()          Returns the current record's "first_name" value
 * @method string      getLastName()           Returns the current record's "last_name" value
 * @method string      getEmail()              Returns the current record's "email" value
 * @method integer     getNbDisplayResults()   Returns the current record's "nb_display_results" value
 * @method string      getLanguage()           Returns the current record's "language" value
 * @method string      getCountry()            Returns the current record's "country" value
 * @method string      getSearchFilter()       Returns the current record's "search_filter" value
 * @method string      getSeries()             Returns the current record's "series" value
 * @method string      getHash()               Returns the current record's "hash" value
 * @method sfGuardUser getUser()               Returns the current record's "User" value
 * @method Profile     setSfGuardUserId()      Sets the current record's "sf_guard_user_id" value
 * @method Profile     setFirstName()          Sets the current record's "first_name" value
 * @method Profile     setLastName()           Sets the current record's "last_name" value
 * @method Profile     setEmail()              Sets the current record's "email" value
 * @method Profile     setNbDisplayResults()   Sets the current record's "nb_display_results" value
 * @method Profile     setLanguage()           Sets the current record's "language" value
 * @method Profile     setCountry()            Sets the current record's "country" value
 * @method Profile     setSearchFilter()       Sets the current record's "search_filter" value
 * @method Profile     setSeries()             Sets the current record's "series" value
 * @method Profile     setHash()               Sets the current record's "hash" value
 * @method Profile     setUser()               Sets the current record's "User" value
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('sf_guard_user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('first_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('nb_display_results', 'integer', 2, array(
             'type' => 'integer',
             'length' => 2,
             ));
        $this->hasColumn('language', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('country', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('search_filter', 'string', 30, array(
             'type' => 'string',
             'length' => 30,
             ));
        $this->hasColumn('series', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('hash', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'sf_guard_user_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));
    }
}