<?php

/**
 * BaseRecurringInvoice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property Doctrine_Collection $Invoices
 * 
 * @method Doctrine_Collection getInvoices() Returns the current record's "Invoices" collection
 * @method RecurringInvoice    setInvoices() Sets the current record's "Invoices" collection
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRecurringInvoice extends Common
{
    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Invoice as Invoices', array(
             'local' => 'id',
             'foreign' => 'recurring_invoice_id'));
    }
}