<?php

/**
 * BaseTemplate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property clob $template
 * @property string $models
 * 
 * @method string   getName()     Returns the current record's "name" value
 * @method clob     getTemplate() Returns the current record's "template" value
 * @method string   getModels()   Returns the current record's "models" value
 * @method Template setName()     Sets the current record's "name" value
 * @method Template setTemplate() Sets the current record's "template" value
 * @method Template setModels()   Sets the current record's "models" value
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTemplate extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('template');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('template', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('models', 'string', 200, array(
             'type' => 'string',
             'length' => 200,
             ));

        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}