<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommonTable extends Doctrine_Table
{
  /**
   * calculate the totals for all invoices (recurring included) if $all is true
   * or for opened and overdue invoices otherwise
   *
   * @return void
   **/
  public static function calculateTotals($all = false)
  {
    if($all)
    {
      $invoices = Doctrine::getTable('Common')->findAll();
    }
    else
    {
      $invoices = InvoiceQuery::create()->status(array(Invoice::OPENED, Invoice::OVERDUE))->execute();
      $recurrings = RecurringInvoiceQuery::create()->execute();
      foreach ($recurrings as $r)
      {
        $r->refresh(true);
        $r->setAmounts()->save();
        unset($r);
      }
    }
    
    foreach ($invoices as $invoice)
    {
      $invoice->refresh(true);
      $invoice->setAmounts()->save();
      unset($invoice);
    }
  }

}