<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class InvoiceTable extends Doctrine_Table
{
  /**
   * Returns the next number for the series
   *
   * @return integer
   * @author Enrique
   **/
  public function getNextNumber($series_id)
  {
    $found = $this->createQuery()
      ->where('Draft = ?', 0)
      ->andWhere('series_id = ?', $series_id)
      ->execute()
      ->count();
    
    if ($found > 0)
    {
      $rs = $this->createQuery()
        ->select('MAX(number) AS max_number')
        ->where('Draft = ?', 0)
        ->andWhere('series_id = ?', $series_id)
        ->fetchOne();
      
      return intval($rs->getMaxNumber()) + 1;
    }
    else
    {
      return Doctrine::getTable('Series')->find($series_id)->getFirstNumber();
    }
  }
  
}