<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ItemTable extends Doctrine_Table
{
  public function retrieveForSelect($q, $limit)
  {
    if (!$limit) $limit = 10;
    
    $items = $this->createQuery()
      ->select('Description')
      ->where('Description LIKE ?', '%'.$q.'%')
      ->distinct()
      ->limit($limit)
      ->execute(array(), Doctrine_Core::HYDRATE_SCALAR);
      
    $res = array();
    foreach ($items as $item)
    {
      $res[] = $item['Item_description'];
    }
    
    return $res;
  }

}