<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Payment extends BasePayment
{
  public function setAmount($v)
  {
    $v = round($v, PropertyTable::get('currency_decimals', 2));

    return $this->_set('amount', $v);
  }
  
  public function postSave($event)
  {
    $this->getInvoice()->checkStatus()->save();
  }
  
  public function postDelete($event)
  {
    $this->getInvoice()->checkStatus()->save();
  }
  
  public function getAmount()
  {
    return (float) $this->_get('amount');
  }
}