<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    siwapp
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{

  public function getPrice()
  {
    return (float) $this->_get('price');
  }
  
  public function  __toString() {
    return $this->getReference();
  }

  /**
   * get the quantity of products invoiced on a certain date_range
   *
   * @return int
   * @author JoeZ99 <jzarate@gmail.com>
   **/
  public function getInvoicedQuantity($date_range = array())
  {
    $items = $this->_table->getInvoicedItems($this->id, $date_range);
    $quantity = 0;
    foreach($items as $i)
    {
      $quantity += $i->getQuantity();
    }
    return (int) $quantity;
  }

  /**
   * get the total sold of products invoiced on a certain date_range
   *
   * @return int
   * @author JoeZ99 <jzarate@gmail.com>
   **/
  public function getInvoicedSold($date_range = array())
  {
    $items = $this->_table->getInvoicedItems($this->id, $date_range);
    $sold = 0;
    foreach($items as $i)
    {
      $sold += $i->quantity * $i->unitary_cost;
    }
    return $sold;
  }
}
