<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Template extends BaseTemplate
{
  /**
   * checks if the template is defined for the model $model
   *
   * @return boolean
   **/
  public function isFor($model)
  {
    $pos = strpos($this->getModels(), $model);
    if ($pos === false)
    {
      return false;
    }
    return true;
  }
}