<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TagTable extends PluginTagTable
{
  public static function getTaggings($tags = array(), $options = array())
  {
    return parent::getTaggings($tags, $options);
  }
}