<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 * Version0 Corresponds to the symfony tag 0.3.4
 */
class Version1 extends Doctrine_Migration_Base
{

  public function preup()
  {
    $customers = Doctrine_Query::create()
      ->select('c.name, c.name_slug')->from('Customer c')->execute();
    $used_names = array();
    $used_slugs = array();
    foreach($customers as $c)
    {
      if(!in_array($c->name, $used_names) && !in_array(CustomerTable::slugify($c->name), $used_slugs))
      {
        $used_names[] = $c->name;
        $used_slugs[] = CustomerTable::slugify($c->name);
      }
      else 
      {
        $counter = 1;
        while(in_array($c->name.'--'.$counter, $used_names) ||
              in_array(CustomerTable::slugify(
                                              $c->name.'--'.$counter),
                                              $used_slugs)
              )
        {
          $counter++;
        }
        $c->name = $c->name.'--'.$counter;
        $c->name_slug = CustomerTable::slugify($c->name);
        $c->save();
      }
    }

  }
  
  public function up()
  {
    $this->removeColumn('customer', 'identification_slug');
    $this->changeColumn('customer', 'name', 'string', '100');
    $this->changeColumn('customer', 'name_slug', 'string', '100');
    $options_name = array('fields' => array('name'),
                          'type' => 'unique'
                          );
    $options_slug = array('fields' => array('name_slug'),
                          'type' => 'unique'
                          );
    $this->removeIndex('customer', 'cstm');
    $this->removeIndex('customer', 'cstid');
    $this->addIndex('customer', 'cstm', $options_name);
    $this->addIndex('customer', 'cstm_slug', $options_slug);
  }
  
  public function down()
  {
    $this->addColumn('customer', 'identification_slug', 'string', '100');
    $this->removeIndex('customer', 'cstm');
    $this->removeIndex('customer', 'cstm_slug');
    $this->addIndex('customer', 'cstm', array('fields'=>array('name')));
    $this->addIndex(
                    'customer', 'cstid', 
                    array('fields'=>array('identification'))
                    );
  }
}