<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('template', 'models', 'string', '200', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('template', 'models');
    }
}