<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('item', 'item_product_id_product_id', array(
             'name' => 'item_product_id_product_id',
             'local' => 'product_id',
             'foreign' => 'id',
             'foreignTable' => 'product',
             'onUpdate' => '',
             'onDelete' => 'SET NULL',
             ));
        $this->addIndex('item', 'item_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('item', 'item_product_id_product_id');
        $this->removeIndex('item', 'item_product_id', array(
             'fields' => 
             array(
              0 => 'product_id',
             ),
             ));
    }
}