<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version3 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('product', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'reference' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '100',
             ),
             'description' => 
             array(
              'type' => 'clob',
              'length' => '',
             ),
             'price' => 
             array(
              'type' => 'decimal',
              'scale' => '15',
              'notnull' => '1',
              'default' => '0',
              'length' => '53',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'utf8',
             ));
        $this->addColumn('item', 'product_id', 'integer', '8', array(
             ));
    }

    public function down()
    {
        $this->dropTable('product');
        $this->removeColumn('item', 'product_id');
    }
}